CREATE DATABASE IF NOT EXISTS fretron;
USE fretron;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  full_name VARCHAR(120) NOT NULL,
  business_name VARCHAR(150) NULL,
  email VARCHAR(160) NOT NULL,
  phone VARCHAR(25) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('user', 'driver', 'transporter', 'admin') NOT NULL DEFAULT 'user',
  account_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'approved',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email),
  UNIQUE KEY uq_users_phone (phone)
);

CREATE TABLE IF NOT EXISTS driver_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  cnic VARCHAR(25) NOT NULL,
  city VARCHAR(80) NOT NULL,
  address VARCHAR(255) NOT NULL,
  license_number VARCHAR(60) NOT NULL,
  license_expiry DATE NOT NULL,
  vehicle_type VARCHAR(60) NOT NULL,
  vehicle_model VARCHAR(80) NOT NULL,
  vehicle_number VARCHAR(30) NOT NULL,
  vehicle_capacity_kg INT NOT NULL,
  profile_picture_url VARCHAR(255) NULL,
  cnic_front_url VARCHAR(255) NULL,
  cnic_back_url VARCHAR(255) NULL,
  license_image_url VARCHAR(255) NULL,
  vehicle_document_url VARCHAR(255) NULL,
  verification_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL,
  rejection_reason VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_driver_user (user_id),
  UNIQUE KEY uq_driver_cnic (cnic),
  UNIQUE KEY uq_driver_license (license_number),
  UNIQUE KEY uq_driver_vehicle_number (vehicle_number),
  CONSTRAINT fk_driver_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_driver_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS transporter_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  owner_name VARCHAR(120) NOT NULL,
  registration_number VARCHAR(80) NOT NULL,
  business_type VARCHAR(80) NOT NULL,
  city VARCHAR(80) NOT NULL,
  address VARCHAR(255) NOT NULL,
  fleet_size INT NOT NULL,
  service_areas VARCHAR(255) NOT NULL,
  has_own_drivers TINYINT(1) NOT NULL DEFAULT 1,
  company_logo_url VARCHAR(255) NULL,
  owner_cnic_front_url VARCHAR(255) NULL,
  owner_cnic_back_url VARCHAR(255) NULL,
  registration_document_url VARCHAR(255) NULL,
  verification_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL,
  rejection_reason VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_transporter_user (user_id),
  UNIQUE KEY uq_transporter_registration (registration_number),
  CONSTRAINT fk_transporter_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_transporter_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shipment_posts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  shipment_code VARCHAR(40) NOT NULL,
  pickup_city VARCHAR(80) NOT NULL,
  destination_city VARCHAR(80) NOT NULL,
  pickup_date DATE NOT NULL,
  preferred_delivery_date DATE NULL,
  parcel_category VARCHAR(100) NOT NULL,
  urgency VARCHAR(40) NOT NULL,
  weight_kg DECIMAL(10,2) NOT NULL,
  dimensions VARCHAR(100) NULL,
  capacity_needed VARCHAR(60) NULL,
  budget DECIMAL(12,2) NULL,
  handling_notes TEXT NULL,
  status ENUM('draft','published','matched','booked','in_transit','delivered','cancelled') NOT NULL DEFAULT 'published',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_shipment_code (shipment_code),
  KEY idx_shipment_user (user_id),
  KEY idx_shipment_status (status),
  CONSTRAINT fk_shipment_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS route_posts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  driver_user_id BIGINT UNSIGNED NOT NULL,
  route_code VARCHAR(40) NOT NULL,
  origin_city VARCHAR(80) NOT NULL,
  destination_city VARCHAR(80) NOT NULL,
  departure_datetime DATETIME NOT NULL,
  estimated_arrival DATETIME NULL,
  available_capacity_kg DECIMAL(10,2) NOT NULL,
  vehicle_type VARCHAR(80) NOT NULL,
  pricing_model VARCHAR(80) NOT NULL,
  price_amount DECIMAL(12,2) NULL,
  restrictions VARCHAR(255) NULL,
  operational_notes TEXT NULL,
  status ENUM('draft','published','partially_booked','completed','cancelled') NOT NULL DEFAULT 'published',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_route_code (route_code),
  KEY idx_route_driver (driver_user_id),
  KEY idx_route_status (status),
  CONSTRAINT fk_route_driver FOREIGN KEY (driver_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  booking_code VARCHAR(40) NOT NULL,
  shipment_post_id BIGINT UNSIGNED NOT NULL,
  route_post_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  driver_user_id BIGINT UNSIGNED NOT NULL,
  requester_role ENUM('user','driver') NOT NULL,
  agreed_price DECIMAL(12,2) NULL,
  booking_status ENUM('pending','accepted','picked_up','in_transit','delivered','cancelled','rejected') NOT NULL DEFAULT 'pending',
  notes TEXT NULL,
  booked_at TIMESTAMP NULL DEFAULT NULL,
  picked_up_at TIMESTAMP NULL DEFAULT NULL,
  delivered_at TIMESTAMP NULL DEFAULT NULL,
  cancelled_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_booking_code (booking_code),
  KEY idx_booking_user (user_id),
  KEY idx_booking_driver (driver_user_id),
  KEY idx_booking_status (booking_status),
  CONSTRAINT fk_booking_shipment FOREIGN KEY (shipment_post_id) REFERENCES shipment_posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_route FOREIGN KEY (route_post_id) REFERENCES route_posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_driver FOREIGN KEY (driver_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking_status_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  booking_id BIGINT UNSIGNED NOT NULL,
  old_status VARCHAR(50) NULL,
  new_status VARCHAR(50) NOT NULL,
  changed_by_user_id BIGINT UNSIGNED NOT NULL,
  note VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_booking_logs_booking (booking_id),
  CONSTRAINT fk_booking_logs_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_logs_user FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(180) NOT NULL,
  body TEXT NOT NULL,
  type VARCHAR(60) NOT NULL DEFAULT 'general',
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  related_booking_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_notifications_user (user_id),
  KEY idx_notifications_read (is_read),
  CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_notification_booking FOREIGN KEY (related_booking_id) REFERENCES bookings(id) ON DELETE SET NULL
);