CREATE DATABASE IF NOT EXISTS fretron;
USE fretron;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  full_name VARCHAR(120) NOT NULL,
  business_name VARCHAR(150) NULL,
  email VARCHAR(160) NOT NULL,
  phone VARCHAR(25) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('user', 'driver', 'transporter', 'admin') NOT NULL DEFAULT 'user',
  account_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'approved',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email),
  UNIQUE KEY uq_users_phone (phone)
);

CREATE TABLE IF NOT EXISTS driver_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  cnic VARCHAR(25) NOT NULL,
  city VARCHAR(80) NOT NULL,
  address VARCHAR(255) NOT NULL,
  license_number VARCHAR(60) NOT NULL,
  license_expiry DATE NOT NULL,
  vehicle_type VARCHAR(60) NOT NULL,
  vehicle_model VARCHAR(80) NOT NULL,
  vehicle_number VARCHAR(30) NOT NULL,
  vehicle_capacity_kg INT NOT NULL,
  profile_picture_url VARCHAR(255) NULL,
  cnic_front_url VARCHAR(255) NULL,
  cnic_back_url VARCHAR(255) NULL,
  license_image_url VARCHAR(255) NULL,
  vehicle_document_url VARCHAR(255) NULL,
  verification_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL,
  rejection_reason VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_driver_user (user_id),
  UNIQUE KEY uq_driver_cnic (cnic),
  UNIQUE KEY uq_driver_license (license_number),
  UNIQUE KEY uq_driver_vehicle_number (vehicle_number),
  CONSTRAINT fk_driver_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_driver_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS transporter_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  owner_name VARCHAR(120) NOT NULL,
  registration_number VARCHAR(80) NOT NULL,
  business_type VARCHAR(80) NOT NULL,
  city VARCHAR(80) NOT NULL,
  address VARCHAR(255) NOT NULL,
  fleet_size INT NOT NULL,
  service_areas VARCHAR(255) NOT NULL,
  has_own_drivers TINYINT(1) NOT NULL DEFAULT 1,
  company_logo_url VARCHAR(255) NULL,
  owner_cnic_front_url VARCHAR(255) NULL,
  owner_cnic_back_url VARCHAR(255) NULL,
  registration_document_url VARCHAR(255) NULL,
  verification_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at TIMESTAMP NULL,
  rejection_reason VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_transporter_user (user_id),
  UNIQUE KEY uq_transporter_registration (registration_number),
  CONSTRAINT fk_transporter_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_transporter_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);
